
torch.Size([64, 16, 16])
Traceback (most recent call last):
  File "/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple_adj.py", line 104, in <module>
    fit(model, optimizer, dataloader, max_epoch=40, device=device)
  File "/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple_adj.py", line 44, in fit
    train_adj_b_noisy_matrix, grad_log_noise_adj_list = gen_list_of_data_single(data, sigma_list, device)
  File "/Users/mmuhleth/Desktop/diffusion_graph/utils/graphs.py", line 30, in gen_list_of_data_single
    train_noise_adj_b, grad_log_q_noise = discretenoise_adj(train_adj_b[count],sigma=sigma_i, config=config)
TypeError: discretenoise_adj() got an unexpected keyword argument 'config'
Traceback (most recent call last):
  File "/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple_adj.py", line 104, in <module>
    fit(model, optimizer, dataloader, max_epoch=40, device=device)
  File "/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple_adj.py", line 44, in fit
    train_adj_b_noisy_matrix, grad_log_noise_adj_list = gen_list_of_data_single(data, sigma_list, device)
  File "/Users/mmuhleth/Desktop/diffusion_graph/utils/graphs.py", line 30, in gen_list_of_data_single
    train_noise_adj_b, grad_log_q_noise = discretenoise_adj(train_adj_b[count],sigma=sigma_i, config=config)
TypeError: discretenoise_adj() got an unexpected keyword argument 'config'